import React from 'react'
import One from "../../../assets/Solar/1.jpeg"



function Solar() {
  return (
    <div className="engineers">
    <div className="container">
    
 
    </div>
    <div className="row">
    <div className="col l12 s12">
    <div>
    <img style={{
        height:200,
        width:"100%"
    }} className='responsive-img' src={One} alt="" />
    </div>
    </div>
 
   
    
    
   
    
    </div>
  

    <div className="row">
  
    <div className="col l6 s12">
    <div>
    <h5>OWN YOUR POWER. SAVE MONEY EVERY MONTH</h5>
    <p>Solar energy is free, abundant and inexhaustible. In the face of global warming, with energy policies calling for wide-scale use of renewable and sustainable technologies, solar power projects are proving increasingly valuable in the reduction of fossil energy. Thanks to technological developments we are now able to convert solar energy into heating or electricity.

   </p>

   <p>How Does Solar Energy Work? Solar energy is energy provided by the Sun. When converted into solar power, it can be used for heating or electricity by private households as well as businesses. Solar power is generated by :</p>

    
    </div>
    </div>
   
    <div className="col l6 s12">
    <div>
    <h5>CONTACT US TODAY:</h5>
    <p>Whether you are considering installing solar panels or a solar thermal collector in your own house or as a business, or if you are just interested in solar energy. We are here to help.</p>

    <h5>1. REQUEST QUOTES</h5>
    <p>Describe your requirements for the product or type of service you need.</p>
<h5>2. RECEIVE QUOTES</h5>
    <p>You will receive up a quote tailored to your needs.</p>

    
    

   
    </div>
    </div>
    </div>
 

    </div>
  )
}



export default Solar
